apiVersion: v1
kind: Template
metadata:
  name: amun-inspect-hwinfo-buildconfig
  annotations:
    description: A buildconfig for Amun's inspect-hwinfo.
    openshift.io/display-name: Amun's inspect-hwinfo buildconfig
    version: 0.0.1
    tags: poc,amun.thoth,ai-stacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      A buildconfig for Amun's inspect-hwinfo.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: amun-inspect-hwinfo-buildconfig
    app: amun
    component: inspect-hwinfo

objects:
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: inspect-hwinfo
      labels:
        app: amun
        component: inspect-hwinfo
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: "inspect-hwinfo:${IMAGE_STREAM_TAG}"
      runPolicy: Serial
      source:
        git:
          uri: ${GITHUB_URL}
          ref: ${GITHUB_REF}
        type: Git
      resources:
        limits:
          memory: '512Mi'
          cpu: '500m'
        requests:
          memory: '512Mi'
          cpu: '500m'
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: python-36-centos7:latest
          env: []
        type: Source
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChange: {}

parameters:
  - description: Name of the github repository
    displayName: Git Repository
    required: true
    name: GITHUB_URL
    value: 'https://github.com/thoth-station/amun-hwinfo'

  - description: Git reference to be used
    displayName: Git Reference
    required: true
    name: GITHUB_REF
    value: 'master'

  - description: Tag of the output ImageStream the resulting container image should go to
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: 'latest'
