apiVersion: v1
kind: Template
metadata:
  name: amun-inspect-hwinfo-imagestream
  annotations:
    description: A imagestream for Amun's inspect-hwinfo.
    openshift.io/display-name: Amun's inspect-hwinfo buildconfig
    version: 0.1.0
    tags: poc,amun.thoth,ai-stacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      An imagestream for Amun's inspect-hwinfo.
    template.openshift.io/provider-display-name: Red Hat, Inc.
    thoth-station.ninja/template-version: 0.1.0
  labels:
    template: amun-inspect-hwinfo-imagestream
    app: amun
    component: inspect-hwinfo

objects:
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      labels:
        app: amun
        component: inspect-hwinfo
      annotations:
        thoth-station.ninja/template-version: 0.1.0
      name: inspect-hwinfo
    spec:
      name: latest
      lookupPolicy:
        local: true
